DELETE http://localhost:3001/api/persons/67dbc7b90071993e3a1b7932
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dd",
    "number" : "02-922-22222"
}

###
PATCH http://localhost:3001/api/persons/67dc0fd2b969b675a27c971c
Content-Type: application/json

{
    "name": "Ann",
    "number": "2417214219787421"
}